### ISSUE TITLE
Multitenant example is not exactly multi-tenant

### ISSUE THREAD

**Issue by pandeybk** [ejaz-ahmed/grails-multitenant-plugin#3]
I tried to run example application (using grails version 3.1.1). Insert and update seems fine, but listing is not working. User (his/his and her/her) display all list.

**Comment by ejaz-ahmed** [comment]
@pandeybk Sorry for responding late. Only grails3.0.x.hibernate4 branch is working. The rest of branches are for GORM5 including master which is broken. Checkout that branch and let me know what you observe?

Checkout this branch https://github.com/ejaz-ahmed/grails-multitenant-plugin/tree/grails3.0.xhibernate4

**Comment by ejaz-ahmed** [comment]
Updated readme to reflect this information.
